import { SpeedInsights } from "@vercel/speed-insights/next"

import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "../components/Sidebar"
import Footer from '../components/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{display: 'grid', gridTemplateColumns: "200px 1fr", backgroundColor: "#f9f9f9", width: "100vw"}}>
          <div style={{width: '200px'}}></div>
          <Sidebar />

          <div>
            {children}
            <SpeedInsights />
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
